<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="68" started-at="2019-10-15T03:31:53Z" finished-at="2019-10-15T03:31:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="68" started-at="2019-10-15T03:31:53Z" finished-at="2019-10-15T03:31:53Z">
      <class name="org.jira.jira_api.LoginAPITesting">
        <test-method status="PASS" signature="getURLData()[pri:0, instance:org.jira.jira_api.LoginAPITesting@b684286]" name="getURLData" is-config="true" duration-ms="21" started-at="2019-10-15T09:01:53Z" finished-at="2019-10-15T09:01:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getURLData -->
        <test-method status="SKIP" signature="createBugTests(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:org.jira.jira_api.LoginAPITesting@b684286]" name="createBugTests" duration-ms="0" started-at="2019-10-15T09:01:53Z" data-provider="getloginData8yiuh" finished-at="2019-10-15T09:01:53Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void org.jira.jira_api.LoginAPITesting.createBugTests(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,org.json.simple.parser.ParseException requires a @DataProvider named : getloginData8yiuh]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void org.jira.jira_api.LoginAPITesting.createBugTests(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException,org.json.simple.parser.ParseException requires a @DataProvider named : getloginData8yiuh
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBugTests -->
      </class> <!-- org.jira.jira_api.LoginAPITesting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
